name: Build and Release Android App

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "9.1.0"

      - name: Decode release keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > my-upload-key.jks

      - name: Build release APK
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/my-upload-key.jks
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: gradle :app:assembleRelease

      - name: Rename APK
        run: |
          cp app/build/outputs/apk/release/app-release.apk Ducky-Mail-Alias-${{ github.ref_name }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Ducky-Mail-Alias-${{ github.ref_name }}.apk
          generate_release_notes: true